name: modern_flutter_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  provider: ^6.1.1
  animate_do: ^3.3.2
  adhan: ^2.0.0
  intl: 0.18.1
  geolocator: ^11.0.0
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.2
  shared_preferences: ^2.2.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: "ic_launcher"
  ios: false
  image_path: "assets/icons/astro_clock_1024.png"
dependency_overrides:
  intl: ^0.20.2